
import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import Navbar from "./navbar/navbar";
import {Inter, Rubik} from "next/font/google"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"]
})
const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {/* <!-- Bootstrap Icons Link --> */}
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css"
        />

        <title>Red Crystal</title>
      </head>
      
      <body  className={`${inter.variable} ${rubik.variable}`}>
        <Navbar/>
        <main className="container-fluid pt-3">
          
          {children}
          
          
        </main>
        <div>
          ©2023-2025 Raymund Dominic L. Crystal. All Rights Reserved.
        </div>
       
         {/* <!-- Bootstrap JS Link --> */}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossOrigin="anonymous"
    ></script>
      </body>
    </html>
  );
}
