import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./navbar";
import Landing from "./landing";
import Contact from "./contact";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {/* <!-- Google Font Roboto Link --> */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Rubik:ital,wght@0,300..900;1,300..900&display=swap"
          rel="stylesheet"
        />

        {/* <!-- Bootstrap CSS Link --> */}
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        />

        {/* <!-- Bootstrap Icons Link --> */}
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css"
        />

        {/* <!-- External CSS --> */}
        <link rel="stylesheet" type="text/css" href="./index.css" />

        <title>Red Crystal</title>
      </head>
      <body>
        <Navbar/>
        <main className="container-fluid pt-3">
          <div id="landing" className="row text-light pt-5 px-5 d-flex flex-column flex-md-row">
            <Landing />
          </div>
          <div className="d-flex flex-column text-light flex-md-row">
             <div id="contact-form" className="m-md-5 m-5">
              <Contact />
             </div>
          </div>
        </main>
         {/* <!-- Bootstrap JS Link --> */}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossOrigin="anonymous"
    ></script>
      </body>
    </html>
  );
}
